#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import { BlobReader, BlobWriter, ZipReader } from "@zip.js/zip.js"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

const RIPGREP_VERSION = "14.1.1"
const RIPGREP_PLATFORM = {
  "arm64-darwin": {
    platform: "aarch64-apple-darwin",
    extension: "tar.gz",
  },
  "arm64-linux": {
    platform: "aarch64-unknown-linux-gnu",
    extension: "tar.gz",
  },
  "x64-darwin": {
    platform: "x86_64-apple-darwin",
    extension: "tar.gz",
  },
  "x64-linux": {
    platform: "x86_64-unknown-linux-musl",
    extension: "tar.gz",
  },
  "x64-win32": {
    platform: "x86_64-pc-windows-msvc",
    extension: "zip",
  },
} as const
const ripgrepCache = new Map<string, Promise<string>>()

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const safeMode = ["1", "true"].includes((process.env.OPENCODE_SAFE_MODE ?? "").toLowerCase())
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : safeMode && !process.env.OPENCODE_MODELS_URL
    ? "{}"
    : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single") || (!!process.env.CI && !process.argv.includes("--all"))
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const abiFlag = process.argv.includes("--musl")
  ? "musl"
  : process.argv.find((item) => item.startsWith("--abi="))?.slice("--abi=".length)

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

function ripgrepName(os: string) {
  return os === "win32" ? "rg.exe" : "rg"
}

function ripgrepID(target: { os: string; arch: "arm64" | "x64" }) {
  return `${target.arch}-${target.os}` as keyof typeof RIPGREP_PLATFORM
}

async function ripgrepExtractTar(input: {
  archive: string
  output: string
  name: string
}) {
  const dest = path.join(input.output, "extract")
  await fs.promises.rm(dest, { recursive: true, force: true })
  await fs.promises.mkdir(dest, { recursive: true })
  await $`tar -xzf ${input.archive} -C ${dest}`

  const list = await Array.fromAsync(new Bun.Glob(`**/${input.name}`).scan({ cwd: dest, onlyFiles: true }))
  const file = list[0]
  if (!file) throw new Error(`ripgrep archive missing ${input.name}: ${input.archive}`)

  const target = path.join(input.output, input.name)
  await fs.promises.copyFile(path.join(dest, file), target)
  await fs.promises.chmod(target, 0o755)
  return target
}

async function ripgrepExtractZip(input: {
  archive: string
  output: string
  name: string
}) {
  const data = await Bun.file(input.archive).arrayBuffer()
  const zip = new ZipReader(new BlobReader(new Blob([data])))
  const entries = await zip.getEntries()
  const entry = entries.find((item) => item.filename.endsWith(input.name))
  if (!entry) throw new Error(`ripgrep archive missing ${input.name}: ${input.archive}`)
  if (!entry.getData) throw new Error(`ripgrep entry cannot be extracted: ${entry.filename}`)

  const blob = await entry.getData(new BlobWriter())
  if (!blob) throw new Error(`failed to extract ${input.name} from ${input.archive}`)

  const target = path.join(input.output, input.name)
  await Bun.write(target, Buffer.from(await blob.arrayBuffer()))
  await zip.close()
  return target
}

async function ripgrepBinary(target: { os: string; arch: "arm64" | "x64" }) {
  const id = ripgrepID(target)
  const config = RIPGREP_PLATFORM[id]
  if (!config) throw new Error(`Unsupported ripgrep target: ${id}`)

  const key = `${config.platform}.${config.extension}`
  const cached = ripgrepCache.get(key)
  if (cached) return cached

  const task = (async () => {
    const filename = `ripgrep-${RIPGREP_VERSION}-${config.platform}.${config.extension}`
    const url = `https://github.com/BurntSushi/ripgrep/releases/download/${RIPGREP_VERSION}/${filename}`
    const root = path.join(dir, "dist", ".tmp", "ripgrep", key)
    const archive = path.join(root, filename)
    const name = ripgrepName(target.os)
    const found = path.join(root, name)
    const exists = await fs.promises
      .stat(found)
      .then((result) => result.isFile())
      .catch(() => false)
    if (exists) return found

    await fs.promises.rm(root, { recursive: true, force: true })
    await fs.promises.mkdir(root, { recursive: true })

    const response = await fetch(url)
    if (!response.ok) throw new Error(`failed to download ripgrep: ${url} (${response.status})`)
    await Bun.write(archive, Buffer.from(await response.arrayBuffer()))

    if (config.extension === "tar.gz") {
      return ripgrepExtractTar({ archive, output: root, name })
    }
    return ripgrepExtractZip({ archive, output: root, name })
  })()
  ripgrepCache.set(key, task)
  return task
}

if (abiFlag && !allTargets.some((item) => item.abi === abiFlag)) {
  throw new Error(`Unsupported abi: ${abiFlag}`)
}

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      if (abiFlag && item.abi !== abiFlag) return false
      if (!abiFlag && item.abi !== undefined) return false
      if (item.avx2 === false) return baselineFlag

      if (
        baselineFlag &&
        allTargets.some(
          (target) =>
            target.os === item.os &&
            target.arch === item.arch &&
            target.abi === item.abi &&
            target.avx2 === false,
        )
      ) {
        return false
      }

      return true
    })
  : allTargets

if (targets.length === 0) {
  throw new Error(`No build targets selected for platform=${process.platform} arch=${process.arch} abi=${abiFlag ?? "default"}`)
}

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  const rg = await ripgrepBinary(item)
  const rgName = ripgrepName(item.os)
  const rgTarget = `dist/${name}/bin/${rgName}`
  await fs.promises.copyFile(rg, rgTarget)
  if (item.os !== "win32") await fs.promises.chmod(rgTarget, 0o755)

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
